version: "3.9"
services:
  mongo:
      image: mongo:4.4.4-bionic
      container_name: mongo
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - "/Volumes/imeepos/mongo/:/data/db"