version: "3.9"

services:
  imeepos:
    depends_on:
      - redis
    build: ./
    volumes:
      - "./scripts:/app"
      - ".env:/app/.env"
    profiles: ["exclude-from-up"]

  redis:
    image: "redis/redis-stack-server:latest"